#
# Description:
# ------------
#
# This is a small test case that creates an enterprise manager with its database,
# a webview.
#

em:
  build: enterprise-manager/9.6.0.0
  links:
    - db:db
  ports:
    - "5001:5001"
    - "8081:8081"
  environment:
    - HEAP="2048m"
  volumes:
    - ~/mm:/root/Introscope/config/modules

db:
  build: database/9.6.0.0

webview:
  build: webview/9.6.0.0
  links:
    - em:em
  ports:
    - "8080:8080"
