#
# Description:
# ------------
#
# This is a small test case that creates an enterprise manager with its database,
# a webview, and ACC Config Server.
#

version: '2'
services:
    em:
        image: apm-em
        links:
            - db:db
        ports:
            - "5001:5001"
            - "8081:8081"
        environment:
            - HEAP="2048m"
        volumes:
#    - ~/mm:/root/Introscope/config/modules
            - ~/git/docker-introscope/transfer/xmltv:/transfer/xmltv
            - ~/git/docker-introscope/transfer/modules:/transfer/modules

    db:
        image: apm-postgres

    webview:
        image: apm-webview
        links:
            - em:em
        ports:
            - "8082:8080"

#configserver:
#  image: "apm-configserver"
#  ports:
#    - "8443:8443"
#    - "8888:8888"
