#
# Description:
# ------------
#
# This is a small test case that creates an enterprise manager with its database,
# a webview.
#

em:
  build: enterprise-manager/9.7.1.16
  links:
    - db:db
  ports:
    - "5001:5001"
    - "8081:8081"
  environment:
    - HEAP="2048m"
  volumes:
#    - ~/mm:/root/Introscope/config/modules
    - ~/git/docker-introscope/transfer/xmltv:/transfer/xmltv
    - ~/git/docker-introscope/transfer/modules:/transfer/modules

db:
  build: database/9.7.1.16

webview:
  build: webview/9.7.1.16
  links:
    - em:em
  ports:
    - "8082:8080"
